export const GET_FACILITIES = "GET_FACILITIES";
export const ADD_FACILITIES = "ADD_FACILITIES";
export const DELETE_FACILITIES = 'DELETE_FACILITIES';
export const EDITE_FACILITIES = 'EDITE_FACILITIES';

export const IS_LODING = 'IS_LODING';

export const ADD_ORGANIC_PRODUCTS = 'ADD_ORGANIC_PRODUCTS';
export const DELETE_ORGANIC_PRODUCTS = 'DELETE_ORGANIC_PRODUCTS';
export const EDITE_ORGANIC_PRODUCTS = 'EDITE_ORGANIC_PRODUCTS';
export const GET_ORGANIC_PRODUCTS = 'GET_ORGANIC_PRODUCTS';

