export const FACILITIES_DATA = "FACILITIES_DATA";

export const DELETE_DATA = "DELETE_DATA"

export const EDIT_DATA = "EDIT_DATA"

export const LOADING_FACILITY = 'LOADING_FACILITY'

export const GET_FACILITIES = 'GET_FACILITIES'

export const GROCERIES_DATA = 'GROCERIES_DATA'

export const DELETE_GROCERIES = 'DELETE_GROCERIES'

export const EDIT_GROCERIES = 'EDIT_GROCERIES'