export const GET_FACILITIES = "GET_FACILITIES";
export const ADD_FACILITIES = "ADD_FACILITIES";
export const DELETE_FACILITIES = 'DELETE_FACILITIES';
export const EDITE_FACILITIES = 'EDITE_FACILITIES';

export const IS_LODING = 'IS_LODING';

export const ADD_PRODUCTS = 'ADD_PRODUCTS';
export const DELETE_PRODUCTS = 'DELETE_PRODUCTS';
export const EDITE_PRODUCTS = 'EDITE_PRODUCTS';
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const ERROR_PRODUCTS = 'ERROR_PRODUCTS';


export const GET_DATA = "GET_DATA";
export const GET_REVIEW = "GET_REVIEW";
export const DELETE_REVIEW = "DELETE_REVIEW";
export const EDITE_REVIEW = "EDITE_REVIEW"

export const ADD_TO_CART = 'ADD_TO_CART';
export const DELETE_TO_CART = 'DELETE_TO_CART';
export const GET_DATA_TO_CART = 'GET_DATA_TO_CART';
export const ERROR = 'ERROR';

export const ADD_TO_COUPON = 'ADD_TO_COUPON';
export const EDIT_TO_COUPON = 'EDIT_TO_COUPON';
export const DELETE_TO_COUPON = 'DELETE_TO_COUPON';
export const GET_DATA_TO_COUPON = 'GET_DATA_TO_COUPON';








